language: java
jdk:
  - oraclejdk8
os:
  - linux
script: mvn clean verify
before_install:
  - sudo pip install codecov
after_success:
  - codecov
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
