language: java
sudo: false
jdk:
  - oraclejdk8
install: true
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
